app/sample/config/routes.rb
Rails.application.routes.draw do
  resources :scores
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/sample/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/sample/app/models/score.rb
class Score < ApplicationRecord
end

app/sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/sample/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = order_model("Score",params[:sort],params[:method])
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :title, :result)
    end
end

app/sample/app/helpers/application_helper.rb
module ApplicationHelper
end

app/sample/app/helpers/scores_helper.rb
module ScoresHelper
end

app/sample/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/sample/app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :score_name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :score_title %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.number_field :result, id: :score_result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/sample/app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/sample/app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th><%= sort_item "#","id" %></th>
      <th><%= sort_item "Name","name" %></th>
      <th><%= sort_item "Title","title" %></th>
      <th><%= sort_item "Result","result" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.id %></td>
        <td><%= score.name %></td>
        <td><%= score.title %></td>
        <td><%= score.result %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/sample/app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/sample/app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @score.title %>
</p>

<p>
  <strong>Result:</strong>
  <%= @score.result %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>